### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by musm** [musm/SLEEF.jl#16]
@JuliaRegistrator register()

**Comment by musm** [comment]
`@JuliaRegistrator approved()`

**Comment by musm** [comment]
@JuliaRegistrator approved()

**Comment by musm** [comment]
@JuliaRegistrator `register()`

**Comment by musm** [comment]
@JuliaRegistrator `register()`

**Comment by musm** [comment]
@JuliaRegistrator `approved()`

**Comment by musm** [comment]
@JuliaRegistrator ` register()`

**Comment by musm** [comment]
@JuliaRegistrator `register()`

**Comment by musm** [comment]
@JuliaRegistrator `register()`

**Comment by musm** [comment]
@JuliaRegistrator `approved()`

**Comment by musm** [comment]
@JuliaRegistrator register()

**Comment by RoyiAvital** [comment]
What the current SLEEF version used under the hood?
