### ISSUE TITLE
Log for small subnormals not accurate to within 1ulp

### ISSUE THREAD

**Issue by musm** [musm/Sleef.jl#2]
upstream issue

julia> Sleef.log(2.0^-1074.)
-744.4400719213559

julia> Base.log(2.0^-1074. |>big)
-7.444400719213812623141072984460816341130871443029141429256103301959047499954517e+02

**Comment by musm** [comment]
upstream issue

**Comment by shibatch** [comment]
Seems correct with the C version?

arg1 = 4.9406564584124654418e-324
test = -744.44007192138121809
corr = -744.44007192138121809

**Comment by musm** [comment]
Yeah it was fixed in version 2.9 for sleef, I'm working on updating the corresponding Julia code 
The issue was with version 2.8

**Comment by shibatch** [comment]
Ah, I didn't see the date of comment
