### ISSUE TITLE
trig functions not accurate for very large argument values

### ISSUE THREAD

**Issue by musm** [musm/Sleef.jl#3]
upstream issue

**Comment by musm** [comment]
upstream issue

**Comment by jiahao** [comment]
Please provide more details

**Comment by musm** [comment]
what more information do you want?

```julia
julia> Sleef.sin(96079.33f0)
2.1360017f-7

julia> Sleef.sin(Float64(96079.33f0))
-2.6335338809697436e-7
```

**Comment by musm** [comment]
Anyways SLEEF isn't a good library for several reasons, which is why I started  from scratch on  `Amal`

**Comment by jiahao** [comment]
It's good to have some examples for people who haven't been following the details.
