### ISSUE TITLE
use zero(T) rather than T(0.0) ?

### ISSUE THREAD

**Issue by oxinabox** [musm/SLEEF.jl#4]
The code is scattersed with `T(0.0)` and `T(1.0)`.
This could be written `zero(T)` and `one(T)`.

Either-way, I believe it should be compiled out of existence.
but for style, I think the latter is to be preferred.

Thoughts?

**Comment by musm** [comment]
My rational was there is a lot of the code that uses `1.0`, `0.0`, and other numeric liters. I thought it would be more uniform to just use `T(0.0)` and `T(2.0)`  and so forth to:
1. Make it clear that these are float values
2. Not have code with both `one(T)` and `T(2.0)` -> everything is consistently numeric literals.

In any case it's not like the code will work for anything other than numeric float types.

**Comment by oxinabox** [comment]
cool, thanks for the insight.
