### ISSUE TITLE
`thanh` is type-unstable on v0.7 

### ISSUE THREAD

**Issue by vchuravy** [musm/SLEEF.jl#7]
Might be a side effect of me being on 0.7, but `thanh(1.0f0)` is type-unstable.

**Comment by musm** [comment]
Sorry for the late response. I just checked and I don't see any type instability. Maybe it was an issue on master that was resolved.

**Comment by RoyiAvital** [comment]
Is there any plan to move to Sleef 3.x branch?

**Comment by musm** [comment]
Yes, but please open a separate issue. Thanks.
